"""empty message

Revision ID: 4f5a8b477723
Revises: 
Create Date: 2024-08-06 06:20:03.614391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5a8b477723'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocked_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=20), nullable=False),
    sa.Column('lastName', sa.String(length=20), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.Column('img', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('posts',
    sa.Column('id_post', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('DRAFTED', 'DELETED', 'PUBLISHED', name='post_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_post'),
    sa.UniqueConstraint('id_post')
    )
    op.create_table('likes',
    sa.Column('id_like', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_like', sa.Integer(), nullable=False),
    sa.Column('post_like', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_like'], ['posts.id_post'], ),
    sa.ForeignKeyConstraint(['user_like'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_like'),
    sa.UniqueConstraint('id_like')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('posts')
    op.drop_table('user')
    op.drop_table('token_blocked_list')
    # ### end Alembic commands ###
